---
- name: Install remote hosts
  hosts: appserver
  vars: 
   remote_dir: /etc/ansible/facts.d
   facts_file: custom.fact
 
  tasks:
    - name: Create remote directory on managed hosts
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"


    - name: Install the custom facts
      copy:
       src: "{{ facts_file }}"
       dest: "{{ remote_dir }}" 
