---
- name: Install Apache and start the service
  hosts: appserver
  tasks:
    - name: Install the required packages
      yum:
       name: "{{ ansible_facts['ansible_local']['custom']['general']['package'] }}"
       state: latest


    - name: Start the apache service
      service:
         name: "{{ansible_facts['ansible_local']['custom']['general']['service'] }}"
         state: "{{ansible_facts['ansible_local']['custom']['general']['state'] }}"
         enabled: "{{ansible_facts['ansible_local']['custom']['general']['enabled'] }}"
